### ISSUE TITLE
Docker-startup.bat fails to run

### ISSUE THREAD

**Issue by patrickml** [brianrufgsa/OSCAL-GUI#18]
When attempting to run Docker-Startup.bat the following error occurs

```sh
C:\**\OSCAL-GUI-master\OSCAL-GUI-master>docker run -p 80:8080 -v "$PWD"/webroot:/var/www/html trafex/alpine-nginx-php7
docker: Error response from daemon: create $PWD/webroot: "$PWD/webroot" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run **--help'.**
```

I believe this is simply because $PWD is not being interpreted by the windows command line, possibly change this to support windows shell or change the extension from .bat to .sh

**Comment by patrickml** [comment]
Here is a docker-compose file that works
```yaml
version: '3.7'

services:
  web:
    container_name: oscal
    image: trafex/alpine-nginx-php7
    volumes:
      - ./webroot/:/var/www/html
    ports:
      - 80:8080
```
